### ISSUE TITLE
discord not detecting rich presence

### ISSUE THREAD

**Issue by blossomflowering** [LilShieru/DAWRPC#4]
Hello, I wanted to send about an issue if this was about the application or just discord not recognizing it well and wondering if this is an issue you could solve, thank you
![Screenshot 2022-03-27 181144](https://user-images.githubusercontent.com/102488259/160301198-a914c2e5-a247-4cc9-9d20-da6ebb5bf4d8.png)

**Comment by LilShieru** [comment]
Actually, I didn't see any errors in this application on my computer; it was just working normally.
Maybe it was because of your Discord? You can try these ways to fix it:
* Try restarting both your Discord application and DAWRPC.
* Try opening both Discord and DAWRPC without administrator permission. You just need to open it normally.
* Make sure that you have enabled **Activity Status** in your Discord application settings.
* Check if there's any antivirus software or firewall that's blocking DAWRPC or Discord.
* You can also try restarting your computer or reinstalling your Discord application.
Also, from next time, you should try troubleshooting your own Discord application or the presence on your computer first before reporting that issue to any Discord Presence Application's Support Page or repository. Just report an issue if you have tried these ways above and it didn't help; and you're sure that the error actually comes from the presence application.
Anyways, thank you for your report, and I'm really sorry about your bad experience with my application.

**Comment by aunight** [comment]
I tried this before but still not working
